-- ============================================================
-- Generic seed helpers (public-safe)
-- ============================================================
--
-- This file intentionally does NOT insert any real-user goals or identity data.
-- In a multi-user deployment, each authenticated user should create their own
-- goals and practices via the app itself or via a dedicated onboarding flow.
--
-- If you want example content for local development, you can either:
--   1) Insert a single demo user and some obviously fictitious goals, or
--   2) Use the Supabase dashboard to import your own personal data into a
--      private project that is not checked into version control.
--
-- Example (commented out) of how you might add generic sample goals:
--
-- INSERT INTO public.goals (user_id, slug, title, domain, description, season, active, sort_order)
-- VALUES
--   ('00000000-0000-0000-0000-000000000000', 'health-foundation', 'Build a sustainable health foundation', 'Health', 'Movement, sleep, and nutrition practices that feel sustainable.', 'Example season', true, 0),
--   ('00000000-0000-0000-0000-000000000000', 'career-growth',     'Invest in long-term career skills',     'Career', 'Regular practice on skills that support the work you want to do.', 'Example season', true, 1),
--   ('00000000-0000-0000-0000-000000000000', 'relationships',     'Deepen close relationships',             'Relationships', 'Simple practices that increase presence and connection.', 'Example season', true, 2)
-- ON CONFLICT (user_id, slug) DO NOTHING;
--
-- For habit and habit_sessions imports, prefer using one-off scripts under
-- the local `scripts/` directory or the Supabase dashboard CSV import feature.
-- Those imports should point at your own private export paths and should not
-- be committed to this repository.
